//! Siralos-owned dynamic loopback-only LSP port allocation.
//!
//! The port is generated by Siralos (never provider input), bound only to
//! `127.0.0.1`, chosen by the OS within its ephemeral range, never
//! scanned across large ranges, race-safe (the OS allocation is the race
//! answer), and bounded in retries. The LSP connection is the only
//! loopback exception to the otherwise offline sandbox profile, and the
//! session reports the isolation scope truthfully.

use std::net::TcpListener;

/// One allocated loopback port; the host is always `127.0.0.1`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AllocatedLspPort {
    /// OS-assigned ephemeral port.
    pub port: u16,
}

/// Bounded allocation attempts before refusal.
pub const MAX_ALLOCATION_ATTEMPTS: usize = 5;

/// Bind a loopback listener on port 0, record the OS-assigned port, then
/// close the listener.
pub fn allocate_loopback_port() -> Result<AllocatedLspPort, String> {
    let mut last_error: Option<String> = None;
    for _ in 0..MAX_ALLOCATION_ATTEMPTS {
        match TcpListener::bind(("127.0.0.1", 0)) {
            Ok(listener) => {
                let port = listener
                    .local_addr()
                    .map_err(|error| error.to_string())?
                    .port();
                drop(listener);
                if port == 0 {
                    last_error = Some(
                        "The OS did not return a valid ephemeral port."
                            .to_owned(),
                    );
                    continue;
                }
                return Ok(AllocatedLspPort { port });
            }
            Err(error) => {
                last_error = Some(error.to_string());
            }
        }
    }
    Err(format!(
        "The loopback LSP port could not be allocated after {MAX_ALLOCATION_ATTEMPTS} attempts: {}",
        last_error.unwrap_or_else(|| "unknown error".to_owned())
    ))
}

/// Verify the port is no longer bound by Siralos (post-session check);
/// a still-bound port is reported truthfully rather than claimed clean.
pub fn release_loopback_port(port: u16) -> Result<(), String> {
    match TcpListener::bind(("127.0.0.1", port)) {
        Ok(listener) => {
            drop(listener);
            Ok(())
        }
        Err(_) => Err(format!(
            "The loopback LSP port {port} is still in use after session cleanup."
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::{
        MAX_ALLOCATION_ATTEMPTS, allocate_loopback_port, release_loopback_port,
    };
    use std::net::TcpListener;

    #[test]
    fn allocates_a_valid_ephemeral_loopback_port() {
        let allocated = allocate_loopback_port().expect("allocation");
        assert!(allocated.port > 0);
        // The port can be bound again after allocation closed its probe.
        release_loopback_port(allocated.port).expect("released");
    }

    #[test]
    fn release_reports_still_bound_ports_truthfully() {
        let listener = TcpListener::bind(("127.0.0.1", 0)).expect("bind");
        let held = listener.local_addr().unwrap().port();
        let error = release_loopback_port(held).expect_err("still bound");
        assert_eq!(
            error,
            format!(
                "The loopback LSP port {held} is still in use after session cleanup."
            )
        );
        drop(listener);
        release_loopback_port(held).expect("free after close");
        let _ = MAX_ALLOCATION_ATTEMPTS;
    }
}
